overrides:
  - files:
      - "*.js"
      - "*.ts"
      - "*.jsx"
      - "*.tsx"
      - "*.mjs"
      - "*.cjs"
      - "*.vue"
      - "*.json"
      - "*.html"
    options:
      plugins:
        - "prettier-plugin-organize-imports"
        - "prettier-plugin-tailwindcss"
      semi: false
      tabWidth: 2
      singleQuote: true
      printWidth: 100
      trailingComma: "all"
      arrowParens: "always"
      organizeImportsSkipDestructiveCodeActions: true
      experimentalTernaries: true
      tailwindConfig: ./app/gui/tailwind.config.ts

  - files: "*.md"
    options:
      printWidth: 80
      proseWrap: "always"
